terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27
terra-money/validator-profiles pull request #375
Opened 2022-06-02 06:31 UTC by Panvasi

https://finder.terra.money/mainnet/validator/terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27

2022-06-03 12:44 UTC, emidev98 requested changes

2022-06-03 12:44 UTC, emidev98 commented on README.md
> +| TERRA-FIRMA              | [Profile](./validators/terravaloper1qqu376azltyc5wnsje5qgwru5mtj2yqdhar97v/README.md) | [Station Page](https://station.terra.money/validator/terravaloper1qqu376azltyc5wns
Hey, could you review this URL? since redirects to the main page of station

2022-06-03 12:44 UTC, emidev98 commented on README.md
> +| Galactic Punks Validator | [Profile](./validators/terravaloper1e6w5qgzs5rzrz8ark25lagm2ga2h9n2tvgzpsl/README.md) | [Station Page](https://station.terra.money/validator/terravaloper1e6w5qgzs5rzrz8ar
Hey, could you review this URL? since redirects to the main page of station

2022-06-04 18:12 UTC, Panvasi commented
finder link: https://finder.terra.money/mainnet/validator/terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27

station link: https://station.terra.money/validator/terravaloper1dmkdw7q23acc72knqv9yu46pz2m363705cnt27

2022-06-06 12:40 UTC, emidev98 commented
Cool! My bad I was pointing to the classic network.

2022-06-06 12:40 UTC, merged