add forbole profile.json
terra-money/validator-profiles pull request #473
Opened 2022-06-22 03:29 UTC by kwunyeung

2022-06-22 17:43 UTC, terran6 commented
If you could add a newline character at the end of your **profile.json** file, then this can be merged. Thanks!

2022-06-24 18:57 UTC, terran6 requested changes
If you could add a simple newline at the end of your **profile.json** file, then this can be merged. Thanks!

2022-06-26 14:29 UTC, kwunyeung commented
@terran6 a new line is added. Thanks!

2022-06-26 20:15 UTC, terran6 approved these changes

2022-06-26 20:17 UTC, merged