Update profile.json
terra-money/validator-profiles pull request #549
Opened 2022-11-10 08:42 UTC by wrjanan

adding notification to check if blocks missed

2022-11-12 11:13 UTC, terran6 requested changes

2022-11-12 11:13 UTC, terran6 commented on validators/terravaloper150w5e8tjk20nfafjzfhyht0aes8a5qr7meh8lg/profile.json
> +      "email": "admin@lunapunks.io" // email to receive notifications
JSON is a data-only format.  Please remove the comments and then we should be good to merge!

2022-11-16 08:44 UTC, terran6 approved these changes

2022-11-16 08:47 UTC, merged

2022-12-24 09:19 UTC, wrjanan commented
Yes, Thank you for fixing @terran6, I will enable mail notifications!