Changed profile - Gridtek.com validator
terra-money/validator-profiles pull request #613
Opened 2023-04-06 11:21 UTC by gridtek

2023-04-07 19:25 UTC, terran6 requested changes

2023-04-11 12:26 UTC, gridtek commented on validators/terravaloper1k0ctjxnyd77lqcww83ldp32el57rww94qsf846/profile.json
> +    "contact": { // contact info for delegators / outreach
Done!

2023-04-11 12:28 UTC, gridtek commented
Done!

2023-04-11 12:42 UTC, terran6 approved these changes

2023-04-11 12:42 UTC, merged