Create validator profile for Terrarium
terra-money/validator-profiles pull request #627
Opened 2023-05-23 01:14 UTC by hanahorangi

2023-05-23 06:15 UTC, terran6 requested changes

2023-05-23 06:15 UTC, terran6 commented on validators/terravaloper1k3202kcypl5csdtyvr3qjmxzzjnyn84ghj2r7y/profile.json
> +    "twitter": "@ClanMudhorn_",
@hanahorangi Please remove the trailing comma to adhere to JSON syntax and then we can merge your profile.  Thanks!

2023-05-23 23:23 UTC, hanahorangi reviewed
Trailing comma removed

2023-05-23 23:23 UTC, hanahorangi reviewed
Trailing comma removed

2023-05-23 23:23 UTC, hanahorangi commented
removed trailing comma

2023-05-24 05:30 UTC, terran6 approved these changes

2023-05-24 05:30 UTC, terran6 approved these changes

2023-05-24 05:32 UTC, merged